export interface BcgAllocationData {
  bcgVaccineAllocated: string;
  bcgDiluentAllocated: string;
  bcg005mlSyringeAllocated: string;
  bcg2mlSyringeAllocated: string;
  bcgVaccineRequested: string;
  bcgDiluentRequested: string;
  bcg005mlSyringeRequested: string;
  bcg2mlSyringeRequested: string;
  bcgVaccineReturned: string;
  bcgDiluentReturned: string;
  bcg005mlSyringeReturned: string;
  bcg2mlSyringeReturned: string;
  bcgVaccineReceived: string;
  bcgDiluentReceived: string;
  bcg005mlSyringeReceived: string;
  bcg2mlSyringeReceived: string;
  bcgEmptyVials: string;
  bcgSafetyBoxes: string;
  bcgUnusedVials: string;
  bcgVaccineConveyorDelivered: string;
  bcgDiluentConveyorDelivered: string;
  bcg005mlSyringeConveyorDelivered: string;
  bcg2mlSyringeConveyorDelivered: string;
  bcgVaccineConveyorReturned: string;
  bcgDiluentConveyorReturned: string;
  bcg005mlSyringeConveyorReturned: string;
  bcg2mlSyringeConveyorReturned: string;
}