export interface MenAAllocationData {
  menAVaccineAllocated: string;
  menADiluentAllocated: string;
  menA05mlSyringeAllocated: string;
  menA5mlSyringeAllocated: string;
  menAVaccineRequested: string;
  menADiluentRequested: string;
  menA05mlSyringeRequested: string;
  menA5mlSyringeRequested: string;
  menAVaccineReturned: string;
  menADiluentReturned: string;
  menA05mlSyringeReturned: string;
  menA5mlSyringeReturned: string;
  menAVaccineReceived: string;
  menADiluentReceived: string;
  menA05mlSyringeReceived: string;
  menA5mlSyringeReceived: string;
  menAEmptyVials: string;
  menASafetyBoxes: string;
  menAUnusedVials: string;
  menAVaccineConveyorDelivered: string;
  menADiluentConveyorDelivered: string;
  menA05mlSyringeConveyorDelivered: string;
  menA5mlSyringeConveyorDelivered: string;
  menAVaccineConveyorReturned: string;
  menADiluentConveyorReturned: string;
  menA05mlSyringeConveyorReturned: string;
  menA5mlSyringeConveyorReturned: string;
}