export interface UploadResponse {
  imported_at: string;
  sheet: string;
  rows_processed: number;
  created: number;
  updated: number;
  errors: Array<{
    sheet_row: number;
    field: string;
    raw: string;
    error: string;
  }>;
}

export interface UploadError {
  message: string;
  errors?: Record<string, string[]>;
}

export interface StockAtHandData {
  id: number;
  serial_no: number;
  state: string;
  lga: string;
  ward: string;
  name_of_ehf: string;
  assigned_unique_id: string;
  distance_km_from_scs: string;
  est_travel_hours_from_scs: string;
  delivery_route: string | null;
  offering_ri_services: string;
  reason_not_offering_ri: string | null;
  cce_count: number;
  cce_model: string;
  cce_functionality_status: string;
  cce_capacity_l: string;
  hard_to_reach: string;
  phone_number: string;
  dose_bcg: number;
  dose_hepb: number;
  dose_bopv: number;
  dose_penta: number;
  dose_pcv: number;
  dose_ipv: number;
  dose_mea: number;
  dose_yf: number;
  dose_td: number;
  dose_mena: number;
  dose_rota: number;
  dose_hpv: number;
  mr: number;
  total_vaccine_storage_volume_utilized: string;
  remaining_cce_storage_capacity: string;
  remark: string | null;
  created_at: string;
  updated_at: string;
}

export interface AllocationSubmitData {
  ehf_id: number;
  assigned_unique_id: string;
  period: string;
  dose_bcg_actual: number;
  dose_bcg_allocated: number;
  bcg_empty_vials?: number;
  bcg_safety_boxes?: number;
  bcg_unused_vials?: number;
  dose_hepb_actual: number;
  dose_hepb_allocated: number;
  hepb_empty_vials?: number;
  hepb_safety_boxes?: number;
  hepb_unused_vials?: number;
  dose_bopv_actual: number;
  dose_bopv_allocated: number;
  bopv_empty_vials?: number;
  bopv_safety_boxes?: number;
  bopv_unused_vials?: number;
  dose_penta_actual: number;
  dose_penta_allocated: number;
  penta_empty_vials?: number;
  penta_safety_boxes?: number;
  penta_unused_vials?: number;
  dose_pcv_actual: number;
  dose_pcv_allocated: number;
  pcv_empty_vials?: number;
  pcv_safety_boxes?: number;
  pcv_unused_vials?: number;
  dose_ipv_actual: number;
  dose_ipv_allocated: number;
  ipv_empty_vials?: number;
  ipv_safety_boxes?: number;
  ipv_unused_vials?: number;
  dose_mea_actual: number;
  dose_mea_allocated: number;
  mea_empty_vials?: number;
  mea_safety_boxes?: number;
  mea_unused_vials?: number;
  dose_yf_actual: number;
  dose_yf_allocated: number;
  yf_empty_vials?: number;
  yf_safety_boxes?: number;
  yf_unused_vials?: number;
  dose_td_actual: number;
  dose_td_allocated: number;
  td_empty_vials?: number;
  td_safety_boxes?: number;
  td_unused_vials?: number;
  dose_mena_actual: number;
  dose_mena_allocated: number;
  mena_empty_vials?: number;
  mena_safety_boxes?: number;
  mena_unused_vials?: number;
  dose_rota_actual: number;
  dose_rota_allocated: number;
  rota_empty_vials?: number;
  rota_safety_boxes?: number;
  rota_unused_vials?: number;
  dose_hpv_actual: number;
  dose_hpv_allocated: number;
  hpv_empty_vials?: number;
  hpv_safety_boxes?: number;
  hpv_unused_vials?: number;
  batch_no?: string;
  threepl?: string;
}

// New nested structure for bulk allocation submission
export interface AllocationItemData {
  assigned_unique_id: string;
  ehf_id: number;
  dose_bcg_actual: number;
  dose_bcg_allocated: number;
  bcg_vvm_stage_scs?: string;
  bcg_batch_number_scs?: string;
  bcg_expire_date_scs?: string | null;
  dose_hepb_actual: number;
  dose_hepb_allocated: number;
  hepb_vvm_stage_scs?: string;
  hepb_batch_number_scs?: string;
  hepb_expire_date_scs?: string | null;
  dose_bopv_actual: number;
  dose_bopv_allocated: number;
  bopv_vvm_stage_scs?: string;
  bopv_batch_number_scs?: string;
  bopv_expire_date_scs?: string | null;
  dose_penta_actual: number;
  dose_penta_allocated: number;
  penta_vvm_stage_scs?: string;
  penta_batch_number_scs?: string;
  penta_expire_date_scs?: string | null;
  dose_pcv_actual: number;
  dose_pcv_allocated: number;
  pcv_vvm_stage_scs?: string;
  pcv_batch_number_scs?: string;
  pcv_expire_date_scs?: string | null;
  dose_ipv_actual: number;
  dose_ipv_allocated: number;
  ipv_vvm_stage_scs?: string;
  ipv_batch_number_scs?: string;
  ipv_expire_date_scs?: string | null;
  dose_mea_actual: number;
  dose_mea_allocated: number;
  mea_vvm_stage_scs?: string;
  mea_batch_number_scs?: string;
  mea_expire_date_scs?: string | null;
  dose_yf_actual: number;
  dose_yf_allocated: number;
  yf_vvm_stage_scs?: string;
  yf_batch_number_scs?: string;
  yf_expire_date_scs?: string | null;
  dose_td_actual: number;
  dose_td_allocated: number;
  td_vvm_stage_scs?: string;
  td_batch_number_scs?: string;
  td_expire_date_scs?: string | null;
  dose_mena_actual: number;
  dose_mena_allocated: number;
  mena_vvm_stage_scs?: string;
  mena_batch_number_scs?: string;
  mena_expire_date_scs?: string | null;
  dose_rota_actual: number;
  dose_rota_allocated: number;
  rota_vvm_stage_scs?: string;
  rota_batch_number_scs?: string;
  rota_expire_date_scs?: string | null;
  dose_hpv_actual: number;
  dose_hpv_allocated: number;
  hpv_vvm_stage_scs?: string;
  hpv_batch_number_scs?: string;
  hpv_expire_date_scs?: string | null;
  dose_mr_actual?: number;
  dose_mr_allocated?: number;
  mr_vvm_stage_scs?: string;
  mr_batch_number_scs?: string;
  mr_expire_date_scs?: string | null;
  slwg_user?: number | null;
}

export interface BulkAllocationSubmitData {
  batch_no: string;
  period: string;
  threepl?: string;
  status: number;
  created_by: number;
  items: AllocationItemData[];
}

export interface AllocatedVaccineData {
  id: number;
  period: string;
  assigned_unique_id: string;
  threepl?: string;
  batch_no?: string;
  batch_status?: number;
  facility_count?: number;
  dose_bcg_actual: number;
  dose_bcg_allocated: number;
  bcg_empty_vials?: number;
  bcg_safety_boxes?: number;
  bcg_unused_vials?: number;
  dose_hepb_actual: number;
  dose_hepb_allocated: number;
  hepb_empty_vials?: number;
  hepb_safety_boxes?: number;
  hepb_unused_vials?: number;
  dose_bopv_actual: number;
  dose_bopv_allocated: number;
  bopv_empty_vials?: number;
  bopv_safety_boxes?: number;
  bopv_unused_vials?: number;
  dose_penta_actual: number;
  dose_penta_allocated: number;
  penta_empty_vials?: number;
  penta_safety_boxes?: number;
  penta_unused_vials?: number;
  dose_pcv_actual: number;
  dose_pcv_allocated: number;
  pcv_empty_vials?: number;
  pcv_safety_boxes?: number;
  pcv_unused_vials?: number;
  dose_ipv_actual: number;
  dose_ipv_allocated: number;
  ipv_empty_vials?: number;
  ipv_safety_boxes?: number;
  ipv_unused_vials?: number;
  dose_mea_actual: number;
  dose_mea_allocated: number;
  mea_empty_vials?: number;
  mea_safety_boxes?: number;
  mea_unused_vials?: number;
  dose_yf_actual: number;
  dose_yf_allocated: number;
  yf_empty_vials?: number;
  yf_safety_boxes?: number;
  yf_unused_vials?: number;
  dose_td_actual: number;
  dose_td_allocated: number;
  td_empty_vials?: number;
  td_safety_boxes?: number;
  td_unused_vials?: number;
  dose_mena_actual: number;
  dose_mena_allocated: number;
  mena_empty_vials?: number;
  mena_safety_boxes?: number;
  mena_unused_vials?: number;
  dose_rota_actual: number;
  dose_rota_allocated: number;
  rota_empty_vials?: number;
  rota_safety_boxes?: number;
  rota_unused_vials?: number;
  dose_hpv_actual: number;
  dose_hpv_allocated: number;
  hpv_empty_vials?: number;
  hpv_safety_boxes?: number;
  hpv_unused_vials?: number;
  dose_mr_actual?: number;
  dose_mr_allocated?: number;
  slwg_user: string | null;
  status: number;
  created_by: string;
  modify_by: string | null;
  date_created: string;
  modify_date: string;
  uuid?: string;
}
