export interface UploadResponse {
  imported_at: string;
  sheet: string;
  rows_processed: number;
  created: number;
  updated: number;
  errors: Array<{
    sheet_row: number;
    field: string;
    raw: string;
    error: string;
  }>;
}

export interface UploadError {
  message: string;
  errors?: Record<string, string[]>;
}

export interface StockAtHandData {
  id: number;
  serial_no: number;
  state: string;
  lga: string;
  ward: string;
  name_of_ehf: string;
  assigned_unique_id: string;
  distance_km_from_scs: string;
  est_travel_hours_from_scs: string;
  delivery_route: string | null;
  offering_ri_services: string;
  reason_not_offering_ri: string | null;
  cce_count: number;
  cce_model: string;
  cce_functionality_status: string;
  cce_capacity_l: string;
  hard_to_reach: string;
  phone_number: string;
  dose_bcg: number;
  dose_hepb: number;
  dose_bopv: number;
  dose_penta: number;
  dose_pcv: number;
  dose_ipv: number;
  dose_mea: number;
  dose_yf: number;
  dose_td: number;
  dose_mena: number;
  dose_rota: number;
  dose_hpv: number;
  total_vaccine_storage_volume_utilized: string;
  remaining_cce_storage_capacity: string;
  remark: string | null;
  created_at: string;
  updated_at: string;
}

export interface AllocationSubmitData {
  ehf_id: number;
  assigned_unique_id: string;
  period: string;
  dose_bcg_actual: number;
  dose_bcg_allocated: number;
  bcg_empty_vials?: number;
  bcg_safety_boxes?: number;
  bcg_unused_vials?: number;
  dose_hepb_actual: number;
  dose_hepb_allocated: number;
  hepb_empty_vials?: number;
  hepb_safety_boxes?: number;
  hepb_unused_vials?: number;
  dose_bopv_actual: number;
  dose_bopv_allocated: number;
  bopv_empty_vials?: number;
  bopv_safety_boxes?: number;
  bopv_unused_vials?: number;
  dose_penta_actual: number;
  dose_penta_allocated: number;
  penta_empty_vials?: number;
  penta_safety_boxes?: number;
  penta_unused_vials?: number;
  dose_pcv_actual: number;
  dose_pcv_allocated: number;
  pcv_empty_vials?: number;
  pcv_safety_boxes?: number;
  pcv_unused_vials?: number;
  dose_ipv_actual: number;
  dose_ipv_allocated: number;
  ipv_empty_vials?: number;
  ipv_safety_boxes?: number;
  ipv_unused_vials?: number;
  dose_mea_actual: number;
  dose_mea_allocated: number;
  mea_empty_vials?: number;
  mea_safety_boxes?: number;
  mea_unused_vials?: number;
  dose_yf_actual: number;
  dose_yf_allocated: number;
  yf_empty_vials?: number;
  yf_safety_boxes?: number;
  yf_unused_vials?: number;
  dose_td_actual: number;
  dose_td_allocated: number;
  td_empty_vials?: number;
  td_safety_boxes?: number;
  td_unused_vials?: number;
  dose_mena_actual: number;
  dose_mena_allocated: number;
  mena_empty_vials?: number;
  mena_safety_boxes?: number;
  mena_unused_vials?: number;
  dose_rota_actual: number;
  dose_rota_allocated: number;
  rota_empty_vials?: number;
  rota_safety_boxes?: number;
  rota_unused_vials?: number;
  dose_hpv_actual: number;
  dose_hpv_allocated: number;
  hpv_empty_vials?: number;
  hpv_safety_boxes?: number;
  hpv_unused_vials?: number;
}

export interface AllocatedVaccineData {
  id: number;
  period: string;
  assigned_unique_id: string;
  dose_bcg_actual: number;
  dose_bcg_allocated: number;
  bcg_empty_vials?: number;
  bcg_safety_boxes?: number;
  bcg_unused_vials?: number;
  dose_hepb_actual: number;
  dose_hepb_allocated: number;
  hepb_empty_vials?: number;
  hepb_safety_boxes?: number;
  hepb_unused_vials?: number;
  dose_bopv_actual: number;
  dose_bopv_allocated: number;
  bopv_empty_vials?: number;
  bopv_safety_boxes?: number;
  bopv_unused_vials?: number;
  dose_penta_actual: number;
  dose_penta_allocated: number;
  penta_empty_vials?: number;
  penta_safety_boxes?: number;
  penta_unused_vials?: number;
  dose_pcv_actual: number;
  dose_pcv_allocated: number;
  pcv_empty_vials?: number;
  pcv_safety_boxes?: number;
  pcv_unused_vials?: number;
  dose_ipv_actual: number;
  dose_ipv_allocated: number;
  ipv_empty_vials?: number;
  ipv_safety_boxes?: number;
  ipv_unused_vials?: number;
  dose_mea_actual: number;
  dose_mea_allocated: number;
  mea_empty_vials?: number;
  mea_safety_boxes?: number;
  mea_unused_vials?: number;
  dose_yf_actual: number;
  dose_yf_allocated: number;
  yf_empty_vials?: number;
  yf_safety_boxes?: number;
  yf_unused_vials?: number;
  dose_td_actual: number;
  dose_td_allocated: number;
  td_empty_vials?: number;
  td_safety_boxes?: number;
  td_unused_vials?: number;
  dose_mena_actual: number;
  dose_mena_allocated: number;
  mena_empty_vials?: number;
  mena_safety_boxes?: number;
  mena_unused_vials?: number;
  dose_rota_actual: number;
  dose_rota_allocated: number;
  rota_empty_vials?: number;
  rota_safety_boxes?: number;
  rota_unused_vials?: number;
  dose_hpv_actual: number;
  dose_hpv_allocated: number;
  hpv_empty_vials?: number;
  hpv_safety_boxes?: number;
  hpv_unused_vials?: number;
  slwg_user: string | null;
  status: number;
  created_by: string;
  modify_by: string | null;
  date_created: string;
  modify_date: string;
}
